#! /usr/bin/env python
import SCons.Builder


# Inherit the parent construction environment
Import("env")


def cprofile(
    program: str = "python -m cProfile",
    required: str = "-o ${TARGET.abspath} -m turbo_turtle._main",
    options: str = "",
    selection: str = "turbo-turtle",
    rows: int = 10
) -> SCons.Builder.Builder:
    """cProfile Builder

    .. code-block::
       :caption: action construction

       ${program} ${required} ${options} >/dev/null
       python -c \"import pstats; p = pstats.Stats('${TARGET.abspath}'); p.sort_stats(pstats.SortKey.CUMULATIVE).print_stats('${selection}', ${rows})\""

    :param program: cProfile command line executable
    :param required: cProfile required options
    :param options: Options for the profiled script

    :returns: SCons cProfile Builder
    """
    action = [
        "${program} ${required} ${options} >/dev/null",
        "python -c \"import pstats; p = pstats.Stats('${TARGET.abspath}'); " \
            "p.sort_stats(pstats.SortKey.CUMULATIVE).print_stats('${selection}', ${rows})\""
    ]
    builder = SCons.Builder.Builder(
        action=action,
        program=program,
        required=required,
        options=options,
        selection=selection,
        rows=rows
    )
    return builder


env.Append(BUILDERS={
    "CProfile": cprofile(),
    "CProfileEager": cprofile(program="EAGER_IMPORT=eager python -m cProfile", rows=0)
})

# Collector alias
target = []

for builder, extension in [(env.CProfile, ".cprofile"), (env.CProfileEager, ".cprofile.eager")]:
    # Package import
    target.extend(builder(
        target=["turbo_turtle_import${extension}"],
        source=["profile_package.py"],
        required="-o ${TARGET.abspath} ${SOURCE.abspath}",
        extension=extension
    ))

    # Help/usage
    target.extend(builder(
        target=["turbo_turtle_help${extension}"],
        source=["cProfile"],
        options="--help",
        extension=extension
    ))

    # Geometry-XYPlot
    target.extend(builder(
        target=["turbo_turtle_geometryxyplot${extension}", "vase${extension}.png"],
        source=["turbo_turtle/tests/vase.csv"],
        options="geometry-xyplot --input-file ${SOURCE.abspath} --output-file ${TARGETS[1].abspath}",
        extension=extension
    ))

env.AlwaysBuild(target)
env.Alias("cProfile", target)
