#! /usr/bin/env python
import numpy

Import(["env"])

target = env.Command(
    target=["help.txt"],
    source=[
        "turbo_turtle/main.py",
        "turbo_turtle/_sphere.py",
        "turbo_turtle/_partition.py",
        "turbo_turtle/_mesh.py",
        "turbo_turtle/_image.py",
        "turbo_turtle/_export.py"
    ],
    action=[
        "python -m turbo_turtle.main -h > ${TARGET.abspath}",
        "python -m turbo_turtle.main docs -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main sphere -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main partition -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main mesh -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main image -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main export -h >> ${TARGET.abspath}"
    ]
)
env.Alias("systemtests", target)
env.Alias("regression", target)

system_tests = (
    # model/part,     angle,   center, quadrant, element_type, element_replacement
    ("sphere",         360., (0., 0.),  "both",  "C3D8",       "C3D8R"),
    ("axisymmetric",     0., (0., 0.),  "both",  "CAX4",       "CAX4R"),
    ("quarter-sphere",  90., (0., 0.),  "both",  "C3D8",       "C3D8R"),
    ("offset-sphere",  360., (1., 1.),  "both",  "C3D8",       "C3D8R"),
    ("eigth-sphere",    90., (0., 0.), "upper",  "C3D8",       "C3D8R"),
    ("half-sphere",    360., (0., 0.), "upper",  "C3D8",       "C3D8R")
)
for model, angle, center, quadrant, element_type, element_replacement in system_tests:
    targets = []
    center_three_dimensions = center + (0,)
    cae_target = env.Command(
        target=[f"{model}.cae"],
        source=["turbo_turtle/main.py", "turbo_turtle/_sphere.py", "turbo_turtle/_partition.py", "turbo_turtle/_mesh.py"],
        action=[
            "python -m turbo_turtle.main sphere --inner-radius 1 --outer-radius 2 --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} --quadrant ${quadrant} " \
                "--angle ${angle} --center ${center}",
            "python -m turbo_turtle.main partition --input-file ${TARGET.abspath} --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} --center ${center} 0 " \
                "--xpoint ${xpoint} --zpoint ${zpoint} --plane-angle 45",
            "python -m turbo_turtle.main mesh --input-file ${TARGET.abspath} --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} --global-seed 0.15 " \
                "--element-type ${element_type}",
        ],
        element_type=element_type,
        quadrant=quadrant,
        angle=angle,
        center=' '.join(map(str, center)),
        xpoint=' '.join(map(str, numpy.array(center_three_dimensions) + numpy.array([1, 0, 0]))),
        zpoint=' '.join(map(str, numpy.array(center_three_dimensions) + numpy.array([0, 0, 1])))
    )
    targets.extend(cae_target)

    png_target = env.Command(
        target=[f"{model}.png"],
        source=[f"{model}.cae", "turbo_turtle/main.py", "turbo_turtle/_image.py"],
        action=[
            "python -m turbo_turtle.main image --input-file ${SOURCE.abspath} --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase}",
        ]
    )
    targets.extend(png_target)

    inp_target = env.Command(
        target=[f"{model}.inp"],
        source=[f"{model}.cae", "turbo_turtle/main.py", "turbo_turtle/_export.py"],
        action=[
            "python -m turbo_turtle.main export --input-file ${SOURCE.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} " \
                "--element-type ${element_replacement} --destination ${TARGET.dir.abspath}",
            "grep ${element_replacement} ${TARGET.abspath}"
        ],
    element_replacement=element_replacement,
    )
    targets.extend(inp_target)

    env.Alias("systemtests", targets)
    env.Alias("regression", targets)


target = env.Command(
    target=["Turbo-Turtle-Tests.cae", "seveneigths-sphere.png", "swiss-cheese.png"],
    source=["legacy_geometry.py"],
    action=[
        "cd ${TARGET.dir.abspath} && abq2023 cae -noGui ${SOURCE.abspath}",
        "${partition_prefix} --part-name seveneigths-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45",
        "${image_prefix} --output-file ${TARGET.dir.abspath}/seveneigths-sphere.png --part-name seveneigths-sphere",
        "${partition_prefix} --part-name swiss-cheese --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45",
        "${image_prefix} --output-file ${TARGET.dir.abspath}/swiss-cheese.png --part-name swiss-cheese",
    ],
    partition_prefix="python -m turbo_turtle.main partition --input-file ${TARGET.abspath} " \
                     "--output-file ${TARGET.abspath} --model-name ${TARGET.filebase} ",
    image_prefix="python -m turbo_turtle.main image --input-file ${TARGET.abspath} --model-name ${TARGET.filebase} "
)
env.Alias("systemtests", target)
env.Alias("regression", target)
