#! /usr/bin/env python
import numpy

Import(["env"])

target = env.Command(
    target=["help.txt"],
    source=[
        "turbo_turtle/main.py",
        "turbo_turtle/_abaqus_python/geometry.py",
        "turbo_turtle/_abaqus_python/cylinder.py",
        "turbo_turtle/_abaqus_python/sphere.py",
        "turbo_turtle/_abaqus_python/partition.py",
        "turbo_turtle/_abaqus_python/mesh.py",
        "turbo_turtle/_abaqus_python/merge.py",
        "turbo_turtle/_abaqus_python/image.py",
        "turbo_turtle/_abaqus_python/export.py"
    ],
    action=[
        "python -m turbo_turtle.main -h > ${TARGET.abspath}",
        "python -m turbo_turtle.main docs -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main geometry -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main cylinder -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main sphere -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main partition -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main mesh -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main image -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main merge -h >> ${TARGET.abspath}",
        "python -m turbo_turtle.main export -h >> ${TARGET.abspath}"
    ]
)
env.Alias("systemtests", target)
env.Alias("regression", target)

system_tests = (
    # model/part,     angle,   center, quadrant, element_type, element_replacement
    ("sphere",         360., (0., 0.),  "both",  "C3D8",       "C3D8R"),
    ("axisymmetric",     0., (0., 0.),  "both",  "CAX4",       "CAX4R"),
    ("quarter-sphere",  90., (0., 0.),  "both",  "C3D8",       "C3D8R"),
    ("offset-sphere",  360., (1., 1.),  "both",  "C3D8",       "C3D8R"),
    ("eigth-sphere",    90., (0., 0.), "upper",  "C3D8",       "C3D8R"),
    ("half-sphere",    360., (0., 0.), "upper",  "C3D8",       "C3D8R")
)
for model, angle, center, quadrant, element_type, element_replacement in system_tests:
    targets = []
    center_three_dimensions = center + (0,)
    cae_target = env.Command(
        target=[f"{model}.cae"],
        source=[
            "turbo_turtle/main.py",
            "turbo_turtle/_abaqus_python/sphere.py",
            "turbo_turtle/_abaqus_python/partition.py",
            "turbo_turtle/_abaqus_python/mesh.py"
        ],
        action=[
            "python -m turbo_turtle.main sphere --inner-radius 1 --outer-radius 2 --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} --quadrant ${quadrant} " \
                "--angle ${angle} --center ${center}",
            "python -m turbo_turtle.main partition --input-file ${TARGET.abspath} --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} --center ${center} 0 " \
                "--xpoint ${xpoint} --zpoint ${zpoint} --plane-angle 45",
            "python -m turbo_turtle.main mesh --input-file ${TARGET.abspath} --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} --global-seed 0.15 " \
                "--element-type ${element_type}",
        ],
        element_type=element_type,
        quadrant=quadrant,
        angle=angle,
        center=' '.join(map(str, center)),
        xpoint=' '.join(map(str, numpy.array(center_three_dimensions) + numpy.array([1, 0, 0]))),
        zpoint=' '.join(map(str, numpy.array(center_three_dimensions) + numpy.array([0, 0, 1])))
    )
    targets.extend(cae_target)

    # Used for merge system tests
    if model == "sphere":
        sphere_target = cae_target[0]

    png_target = env.Command(
        target=[f"{model}.png"],
        source=[f"{model}.cae", "turbo_turtle/main.py", "turbo_turtle/_abaqus_python/image.py"],
        action=[
            "python -m turbo_turtle.main image --input-file ${SOURCE.abspath} --output-file ${TARGET.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase}",
        ]
    )
    targets.extend(png_target)

    inp_target = env.Command(
        target=[f"{model}.inp"],
        source=[f"{model}.cae", "turbo_turtle/main.py", "turbo_turtle/_abaqus_python/export.py"],
        action=[
            "python -m turbo_turtle.main export --input-file ${SOURCE.abspath} " \
                "--model-name ${TARGET.filebase} --part-name ${TARGET.filebase} " \
                "--element-type ${element_replacement} --destination ${TARGET.dir.abspath}",
            "grep ${element_replacement} ${TARGET.abspath}"
        ],
    element_replacement=element_replacement,
    )
    targets.extend(inp_target)

    env.Alias("systemtests", targets)
    env.Alias("regression", targets)

# geometry system tests
system_tests = (
    # model/part,         input_file,                 angle
    ("washer",            'test_geometry_washer.csv', 360.),
    ("vase",              'test_geometry_vase.csv',   360.),
    ("vase-axisymmetric", 'test_geometry_vase.csv',   0.0)
)
for model, input_file, revolution_angle in system_tests:
    target = env.Command(
        target=[f"{model}.cae"],
        source=[f"turbo_turtle/tests/{input_file}", "turbo_turtle/main.py", "turbo_turtle/_abaqus_python/geometry.py"],
        action=[
            "python -m turbo_turtle.main geometry --input-file ${SOURCE.abspath} --model-name ${TARGET.filebase} " \
                "--part-name ${TARGET.filebase} --output-file ${TARGET.abspath} --revolution-angle ${revolution_angle}",
        ],
        revolution_angle=revolution_angle,
    )
    env.Alias("systemtests", target)
    env.Alias("regression", target)

# _cylinder system tests
system_tests = (
    # model/part, angle
    ("cylinder_3d",    360.),
    ("cylinder_2d",      0.)
)
for model, revolution_angle in system_tests:
    target = env.Command(
        target=[f"{model}.cae"],
        source=[f"turbo_turtle/tests/{input_file}", "turbo_turtle/main.py", "turbo_turtle/_abaqus_python/cylinder.py"],
        action=[
            "python -m turbo_turtle.main cylinder --model-name ${TARGET.filebase} --part-name ${TARGET.filebase} " \
                "--output-file ${TARGET.abspath} --revolution-angle ${revolution_angle} " \
                "--inner-radius 1 --outer-radius 2 --height 1"
        ],
        revolution_angle=revolution_angle,
    )
    env.Alias("systemtests", target)
    env.Alias("regression", target)

model = "multi-part-geometry"
revolution_angle = 360.0
target = env.Command(
    target=[f"{model}.cae"],
    source=["turbo_turtle/tests/test_geometry_washer.csv", "turbo_turtle/tests/test_geometry_vase.csv",
             "turbo_turtle/main.py", "turbo_turtle/_abaqus_python/geometry.py"],
    action=[
        "python -m turbo_turtle.main geometry --input-file turbo_turtle/tests/test_geometry_washer.csv " \
            "turbo_turtle/tests/test_geometry_vase.csv --model-name ${TARGET.filebase} " \
            "--output-file ${TARGET.abspath} --revolution-angle ${revolution_angle}"
    ],
    revolution_angle=revolution_angle
)
env.Alias("systemtests", target)
env.Alias("regression", target)
# Used for merge system tests
multi_part_target = target[0]

# merge system tests (requires geometry and sphere targets)
model = "merged-model"
target = env.Command(
    target=[f"{model}.cae"],
    source=[multi_part_target, sphere_target,
            "turbo_turtle/main.py", "turbo_turtle/_abaqus_python/merge.py"],
    action=[
        "python -m turbo_turtle.main merge --input-file ${SOURCES[0].abspath} ${SOURCES[1].abspath} " \
            "--output-file ${TARGET.abspath} --merged-model-name ${TARGET.filebase} " \
            "--model-name multi-part-geometry sphere " \
            "--part-name test_geometry_washer test_geometry_vase sphere",
        "grep -iIre \"SUCCESS\" abaqus.rpy | grep \"part 'test_geometry_washer'\"",
        "grep -iIre \"SUCCESS\" abaqus.rpy | grep \"part 'test_geometry_vase'\"",
        "grep -iIre \"SUCCESS\" abaqus.rpy | grep \"part 'sphere'\"",
    ]
)
env.Alias("systemtests", target)
env.Alias("regression", target)

model = "merged-model-2"
target = env.Command(
    target=[f"{model}.cae"],
    source=[multi_part_target, sphere_target,
            "turbo_turtle/main.py", "turbo_turtle/_abaqus_python/merge.py"],
    action=[
        "python -m turbo_turtle.main merge --input-file ${SOURCES[0].abspath} ${SOURCES[1].abspath} " \
            "--output-file ${TARGET.abspath} --merged-model-name ${TARGET.filebase}",
        "grep -iIre \"SUCCESS\" abaqus.rpy | grep \"part 'test_geometry_washer'\"",
        "grep -iIre \"SUCCESS\" abaqus.rpy | grep \"part 'test_geometry_vase'\"",
        "grep -iIre \"SUCCESS\" abaqus.rpy | grep \"part 'sphere'\"",
    ]
)
env.Alias("systemtests", target)
env.Alias("regression", target)

target = env.Command(
    target=["Turbo-Turtle-Tests.cae", "seveneigths-sphere.png", "swiss-cheese.png"],
    source=["legacy_geometry.py"],
    action=[
        "cd ${TARGET.dir.abspath} && abq2023 cae -noGui ${SOURCE.abspath}",
        "${partition_prefix} --part-name seveneigths-sphere --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45",
        "${image_prefix} --output-file ${TARGET.dir.abspath}/seveneigths-sphere.png --part-name seveneigths-sphere",
        "${partition_prefix} --part-name swiss-cheese --center 0 0 0 --xpoint 1 0 0 --zpoint 0 0 1 --plane-angle 45",
        "${image_prefix} --output-file ${TARGET.dir.abspath}/swiss-cheese.png --part-name swiss-cheese",
    ],
    partition_prefix="python -m turbo_turtle.main partition --input-file ${TARGET.abspath} " \
                     "--output-file ${TARGET.abspath} --model-name ${TARGET.filebase} ",
    image_prefix="python -m turbo_turtle.main image --input-file ${TARGET.abspath} --model-name ${TARGET.filebase} "
)
env.Alias("systemtests", target)
env.Alias("regression", target)
