#! /usr/bin/env python

import pathlib

# Inherit the parent construction environment
Import("env")

# Limit list of source files to allow Conda build-test to test off the installed package
waves_source_list = [
    "pyproject.toml",
]

pytest_command = "PYTHONDONTWRITEBYTECODE=1 pytest --junitxml=${TARGET.abspath}"
target = ["test_results.xml"]

targets = env.Command(
    target=target,
    source=waves_source_list,
    action=[
        "${pytest_command} -vvv",
    ],
    pytest_command=pytest_command
)
env.Alias("pytest", targets)
env.Alias("unittests", targets)
# Always run pytests in place of a complete source list
env.AlwaysBuild(targets)

# Collector alias to build all regression tasks
env.Alias("regression", targets)
