#! /usr/bin/env python

import pathlib

# Inherit the parent construction environment
Import("env")

# Limit list of source files to allow Conda build-test to test off the installed package
pytest_source_list = [
    "pyproject.toml",
]

pytest_command = "PYTHONDONTWRITEBYTECODE=1 pytest --junitxml=${TARGET.abspath}"
target = ["test_results.xml"]

targets = env.Command(
    target=target,
    source=pytest_source_list,
    action=[
        "${pytest_command} -vvv",
    ],
    pytest_command=pytest_command
)
env.Alias("pytest", targets)
env.Alias("unittests", targets)
env.Alias("regression", targets)
# Always run pytests in place of a complete source list
env.AlwaysBuild(targets)

target = ["test_abaqus_python.txt"]
source = ["turbo_turtle/_abaqus_python/test_abaqus_utilities.py"]
targets = env.Command(
    target=target,
    source=source,
    action=[
        "${program} python ${SOURCES} --verbose 2>&1 | tee test_abaqus_python.txt"
    ],
    program=env["abaqus"]
)
env.Alias("test_abaqus", targets)
env.Alias("unittests", targets)
env.Alias("regression", targets)
# Always run pytests in place of a complete source list
env.AlwaysBuild(targets)
