#! /usr/bin/env python
import os
import inspect
import pathlib

import waves

import turbo_turtle

AddOption(
    "--uninstalled",
    dest="uninstalled",
    default=False,
    action="store_true",
    help="Boolean to use the uninstalled, repository Turbo-Turtle command 'python -m turbo_turtle.main'. " \
         "(default: '%default')"
)

project_configuration = pathlib.Path(inspect.getfile(lambda: None))
project_directory = project_configuration.parent

env = Environment(
    ENV=os.environ.copy(),
    uninstalled=GetOption("uninstalled"),
)
env["abaqus"] = waves.scons_extensions.add_program(["/apps/abaqus/Commands/abq2023", "abq2023"], env)
env["cubit"] = waves.scons_extensions.add_cubit(["/apps/Cubit-16.12/cubit", "cubit"], env)
env["turbo_turtle"] = "python -m turbo_turtle.main" if env["uninstalled"] else "turbo-turtle"
env.Append(BUILDERS={
    "TurboTurtleGeometry": turbo_turtle.scons_extensions.builder("geometry"),
    "TurboTurtleGeometryXYPlot": turbo_turtle.scons_extensions.builder("geometry-xyplot"),
    "TurboTurtleMerge": turbo_turtle.scons_extensions.builder("merge"),
    "TurboTurtleSphere":
        turbo_turtle.scons_extensions.turbo_turtle_sphere(program=env["turbo_turtle"],
                                                          abaqus_command=[env['abaqus']]),
    "TurboTurtlePartition":
        turbo_turtle.scons_extensions.turbo_turtle_partition(program=env["turbo_turtle"],
                                                             abaqus_command=[env['abaqus']]),
    "TurboTurtleSphereCubit":
        turbo_turtle.scons_extensions.turbo_turtle_sphere(program=env["turbo_turtle"],
                                                          cubit_command=[env['cubit']], cubit=True),
    "TurboTurtlePartitionCubit":
        turbo_turtle.scons_extensions.turbo_turtle_partition(program=env["turbo_turtle"],
                                                             cubit_command=[env['cubit']], cubit=True),
})

# API builders
cubit_flag = [
    (False, ".cae"),  # Use Abaqus as backend
    (True, ".cub")  # Use Cubit as backend
]
for flag, extension in cubit_flag:

    # Geometry
    env.TurboTurtleGeometry(
        target=[f"scons-vase{extension}"],
        source=[str(project_directory / "vase.csv")],
        cubit=flag,
        output_file="${TARGET.abspath}",
        model_name="scons-vase",
        part_name=["scons-vase"]
    )
    env.TurboTurtleGeometry(
        target=[f"scons-washer{extension}"],
        source=[str(project_directory / "washer.csv")],
        cubit=flag,
        output_file="${TARGET.abspath}",
        model_name="scons-washer",
        part_name=["scons-washer"]
    )
    env.TurboTurtleGeometry(
        target=[f"scons-multi-part{extension}"],
        source=[
            str(project_directory / "vase.csv"),
            str(project_directory / "washer.csv")
        ],
        cubit=flag,
        output_file="${TARGET.abspath}",
        model_name="scons-multi-part",
        part_name=["scons-vase", "scons-washer"]
    )

    # Geometry-XY Plot
    env.TurboTurtleGeometryXYPlot(
        target=[f"scons-vase{extension}.png"],
        source=[str(project_directory / "vase.csv")],
        cubit=flag,
        output_file="${TARGET.abspath}",
        part_name=["scons-vase"]
    )
    env.TurboTurtleGeometryXYPlot(
        target=[f"scons-washer{extension}.png"],
        source=[str(project_directory / "washer.csv")],
        cubit=flag,
        output_file="${TARGET.abspath}",
        part_name=["scons-washer"]
    )
    env.TurboTurtleGeometryXYPlot(
        target=[f"scons-multi-part{extension}.png"],
        source=[
            str(project_directory / "vase.csv"),
            str(project_directory / "washer.csv")
        ],
        cubit=flag,
        output_file="${TARGET.abspath}",
        part_name=["scons-vase", "scons-washer"]
    )

    # Sphere
    # Cylinder
    # Partition
    # Mesh
    # Image
    # Merge
    env.TurboTurtleMerge(
        target=[f"scons-merge-multi-part{extension}"],
        source=[f"scons-vase{extension}", f"scons-washer{extension}"],
        cubit=flag,
        output_file="${TARGET.abspath}",
        model_name=["scons-vase", "scons-washer"],
        part_name=["scons-vase", "scons-washer"],
        merged_model_name="scons-merge-multi-part"
    )


# CLI builders
env.TurboTurtleSphere(
    target=["scons-cli-sphere.cae"],
    source=[str(project_configuration)],
    inner_radius=1.,
    outer_radius=2.,
    model_name="sphere",
    part_name="sphere"
)
env.TurboTurtlePartition(
    target=["scons-cli-partition.cae"],
    source=["scons-cli-sphere.cae"],
    model_name="sphere",
    part_name="sphere"
)
env.TurboTurtleSphereCubit(
    target=["scons-cli-sphere.cub"],
    source=[str(project_configuration)],
    inner_radius=1.,
    outer_radius=2.,
    model_name="sphere",
    part_name="sphere"
)
env.TurboTurtlePartitionCubit(
    target=["scons-cli-partition.cub"],
    source=["scons-cli-sphere.cub"],
    model_name="sphere",
    part_name="sphere"
)

waves.scons_extensions.project_help_message()
