{% set name = "turbo_turtle" %}
{% set version = VERSION %}

package:
  name: {{ name|lower }}
  # TODO: Figure out how to use pyproject.toml and a Conda build Jinja template
  version: {{ version }}


source:
  git_url: '..'

# NOTE: CANNOT use noarch builds. conda-build will not use python variants if the package is marked "noarch: python"
build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - scons install --prefix=${PREFIX}  # [unix]
    - scons install --prefix=%PREFIX%  # [win]
  entry_points:
    - turbo-turtle = turbo_turtle._main:main

requirements:
  host:
    # Force consistency in the Python build version
    - python {{ python }}
    - scons {{ scons }}
    - python-build
    - pip
    - pytest
    - lazy_loader >=0.4
    - setuptools >=77
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx-book-theme
    - sphinxcontrib-bibtex
    - waves >=0.13
  run:
    # Force a Python variant package build
    - python {{ python }}
    - lazy_loader >=0.4
    # Force an SCons variant package build
    - scons {{ scons }}
    - waves >=0.13

test:
  requires:
    # Force a Python variant package test
    - python {{ python }}
    - pip
    - pytest
    - pytest-xdist
    - python-gmsh >=4
    - waves >=0.13
  imports:
    - turbo_turtle

about:
  home: https://re-git.lanl.gov/aea/python-projects/turbo_turtle
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved models
  description: |
    Turbo-Turtle (LANL code O4765) is a solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved
    models.
  doc_url: https://aea.re-pages.lanl.gov/python-projects/turbo_turtle/main/index.html
  dev_url: https://re-git.lanl.gov/aea/python-projects/turbo_turtle
