{% set name = "turbo_turtle" %}
{% set version = VERSION %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  # TODO: Figure out how to use pyproject.toml and a Conda build Jinja template
  version: {{ version }}

source:
  git_url: '..'

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - scons install --prefix=${PREFIX}  # [unix]
    - scons install --prefix=%PREFIX%  # [win]
  entry_points:
    - turbo-turtle = turbo_turtle._main:main

requirements:
  host:
    - python-build
    - python-gmsh >=4
    - pip
    - pytest
    - lazy_loader >=0.4
    - matplotlib-base >=3
    - scons >=4.6
    - setuptools >=77
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-book-theme
    - sphinx-copybutton >=0.5.1
    - sphinx-design
    - sphinxcontrib-bibtex
    - waves >=0.13
  run:
    - python >={{ python_min }}
    - lazy_loader >=0.4
    - matplotlib-base >=3
    - scons >=4.6
    - waves >=0.13

test:
  requires:
    - pip
    - pytest
    - pytest-xdist
    - python-gmsh >=4
  imports:
    - turbo_turtle

about:
  home: https://re-git.lanl.gov/aea/python-projects/turbo_turtle
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved models
  description: |
    Turbo-Turtle (LANL code O4765) is a solid body modeling tools for 2D sketched, 2D axisymmetric, and 3D revolved
    models.
  doc_url: https://aea.re-pages.lanl.gov/python-projects/turbo_turtle/main/index.html
  dev_url: https://re-git.lanl.gov/aea/python-projects/turbo_turtle
